### ISSUE TITLE
Anyone with "Admin users" edit permissions can make anyone a Head

### ISSUE THREAD

**Issue by davedujour** [ConOnRails/ConOnRails#101]
Any user with "Admin users" can make any user a Head, Subhead, etc. \A user shouldn't be able to give permissions for access that user doesn't have, i.e. a user without "Read hidden entries" permissions shouldn't be able to give any user (including themselves) access to a Role with "Read hidden entries" permissions.

**Comment by mshappe** [comment]
This is as designed. Don't give Admin Users permissions to people you don't trust.

**Comment by wmamurphy** [comment]
Without a report or other mechanism to reset individual members , a person could (in theory) pull a complete file of all issues logged for the convention.  Using a "trust but verify" approach only works if we can easily clean up the Chase P.'s who were added as Admins and then lost for 2 years.
