### ISSUE TITLE
As a user, the Enter key now creates spaces and there is no way to get a Line Break.

### ISSUE THREAD

**Issue by wmamurphy** [ConOnRails/ConOnRails#137]
Testing the Dependencies has identified there is now no way to get a line break to appear in an entry in Firefox 98.0.1 in Linux or 98.0.2 on Windows 10.  

This issue does NOT occur in: 
Chrome 100.0.4896.60 on Windows 10 
Opera on Win10
Microsoft Edge on Win 10

The DISPLAY does work accurately, it is the entry box that is borked.

**Comment by mshappe** [comment]
Only Chrome and Chromium-based browsers are supported. I no longer test with Firefox, and do not intend to make much effort there.
