### ISSUE TITLE
As a Bridge Guru, the Radio check-in function is not allowing a user to confirm their choice.

### ISSUE THREAD

**Issue by wmamurphy** [ConOnRails/ConOnRails#140]
In addition, Test Environment radio check-in is buggy under the latest version of Firefox & Chrome.  The "Are You Sure" window flashes for only an instant.  It's barely readable, and there's a very short reaction window.

**Comment by wmamurphy** [comment]
This issues exists in Test & Production.

**Comment by mshappe** [comment]
@wmamurphy I am unable to reproduce this. Radio check in is working perfectly for me, as expected, with Are You Sure appearing and waiting for input as it should.

**Comment by wmamurphy** [comment]
Appears to be working correctly now.

**Comment by gwessend** [comment]
Issue appears to have been specific to Firefox, and persists in 102.0.1

**Comment by mshappe** [comment]
As the joke goes, "If it hurts when you do that, don't do that."

Firefox is not supported at this time.
