### ISSUE TITLE
As a l&f user, on the search page, I would like "find any word" to be default, rather than find all words.  

### ISSUE THREAD

**Issue by mshappe** [ConOnRails/ConOnRails#67]
I'd like to discuss this one before we take action. I'm not convinced.

**Comment by wmamurphy** [comment]
4/16/2021 - Discussed in 2019 & 2020 with end users.  They are unanimous that this feature needs to be added.

**Comment by davedujour** [comment]
Discussed again in 2021. This still needs to be implemented.

**Comment by mshappe** [comment]
The most likely path to this being implemented will be for Operations to recruit a Ruby on Rails programmer I can mentor through the process.
