### ISSUE TITLE
For developers, Dockerize the application

### ISSUE THREAD

**Issue by BenOvermyer** [ConOnRails/ConOnRails#72]
Dockerizing the application will make it easier for new developers to get started on the project.

**Note:** this is only for development. Creating a Docker process for production release is outside the scope of this issue.

**Comment by mshappe** [comment]
Agreed on both points. I don't think dockerising is **essential** for developers, given that Homebrew etc are not exactly hard to set up, but it is **easier** if you can just run a script that pulls down images and runs containers that have all the pieces in them. I'm in the process of dockerising for both development and eventually production in my day-job, and I'm increasingly a fan.

**Comment by BenOvermyer** [comment]
Essential? No, it's not. However, it minimizes the number of "works in dev" issues that might crop up, since the development environment is identical at that point.
