### ISSUE TITLE
If a "#" is used at the beginning of a line, the following text is created at a 24+ pt font

### ISSUE THREAD

**Issue by wmamurphy** [ConOnRails/ConOnRails#91]
As a user, using a "#" (as a hashtag) I was attempting to create a hastag for identification post-con.  Instead, the use of that character at the beginning of the line caused the line to be at a 24+ point font.  This effect should be removed so the control character does not affect the display of the data.

**Comment by wmamurphy** [comment]
On 4/16/2021 - This is still an existing issue.  See ID 110.

**Comment by mshappe** [comment]
This is not an issue. This is intended behaviour. Text boxes use Markdown; pound-signs mark out headers in Markdown. Don't start a line with a pound sign unless you mean it.
